### ISSUE TITLE
Does not install on Server 2012 R2

### ISSUE THREAD

**Issue by blysspluss** [chocolatey/puppet-chocolatey_server#12]
The initial Import-Module WebAdministration fails(Because the IIS parts are not installed with current code) which causes rapid fail on all other items. I'm unclear on why.

**Comment by ferventcoder** [comment]
PE 2016.5 is where this is being seen.

**Comment by blysspluss** [comment]
Looks like it was related to issue with puppet-windowsfeature. Updating to latest module version solved this. Updating puppet-IIS module to 3.0.0 causes new failures, though. I get error:  Unknown resource type: 'iis::manage_site' at /etc/puppetlabs/code/environments/development/modules/chocolatey_server/manifests/init.pp:71:3

**Comment by ferventcoder** [comment]
IIS 3.x I think removed the deprecated way we were doing to manage things. I think it is likely safe to move up to the new way.

**Comment by ferventcoder** [comment]
Just moved this over to puppetlabs-iis, so it's likely this is no longer an issue.
