### ISSUE TITLE
Dependency on puppetlabs-powershell

### ISSUE THREAD

**Issue by covidium** [chocolatey/puppet-chocolatey_server#13]
The guys from puppetlabs released v.2.1.0 while this module requires 2.0.0

**Comment by ferventcoder** [comment]
I'm confused - https://github.com/chocolatey/puppet-chocolatey_server/blob/f7eb90ddf874aed5e855d822a5c41f9d764b970f/metadata.json#L40:

~~~json
   {
      "name": "puppetlabs/powershell",
      "version_requirement": ">= 1.0.4 < 3.0.0"
    },
~~~

Allows for at least 1.0.4 up to any version under 3. Are you seeing otherwise?

**Comment by ferventcoder** [comment]
Ah, just checked the last released version - it was under v2 - https://forge.puppet.com/chocolatey/chocolatey_server/dependencies

Sounds like we should get a release out for that.

**Comment by covidium** [comment]
Another dependency issue is puppet/windowsfeature which now is 2.1.0.
Btw, do you have an ETA for the new release?

**Comment by ferventcoder** [comment]
@covidium probably sometime before PuppetConf.

**Comment by ferventcoder** [comment]
This will be pushed sometime soon.
